### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by danielrheinbay** [mfa/meinsack-datasette#1]
Good news: I am not sure since when, but I just noticed the official API of Abfallwirtschaft Stuttgart now includes Gelber Sack dates as well! Generate an ical URL for your place at https://service.stuttgart.de/lhs-services/aws/abfallkalender

May be it's time to archive this repo?

**Comment by mfa** [comment]
1) I use the json api of meinsack - not only the ical calendar
2) This second version was to do something with datasette

The old version is archived, because it was a pain to update the DRF hacks in it.
